dist: xenial
language: python
python: 3.8
install:
  - pip install -r requirements_dev.txt
  - pip install -e .

script:
  — pytest --cov=Parser_Yandex.py
  — pytest --cov=ParserGoogle.py
  — pytest --cov=Parser.py
after_success:
  — coveralls
